services:
  mysql:
    image: mysql:8.4
    container_name: ventas-libros-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_appbibliotca
    ports:
      - "3306:3306"
    volumes:
      - ventas_libros_mysql_data:/var/lib/mysql
volumes:
  ventas_libros_mysql_data:
