server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: ventas-libros
  datasource:
    url: postgresql://postgres:aTyZlwYmdPfwHgfqksuXtTujJtOOBHwH@postgres.railway.internal:5432/railway
    username: postgres
    password: aTyZlwYmdPfwHgfqksuXtTujJtOOBHwH
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

app:
  jwt:
    secret: "0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF"
    expiration-ms: 86400000
